config/routes.rb
Sportsalliance::Application.routes.draw do  resources :events
  resources :charges

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                   controllers: {omniauth_callbacks: "omniauth_callbacks"}

  get "faq" => "pages#faq"
  get "team" => "pages#team"
  get "howitworks" => "pages#how-it-works"
  get "contact" => "pages#contact"
  get "myteams" => "pages#myteams"
  get "myevents" => "pages#myevents"
  root "pages#home"

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  get "/events/:id/checkout" => "events#checkout", :as => "event_checkout"
  get "/events/:id/invite-facebook-friends" => "events#invite", :as => "event_invite"
  post "/events/:id/register" => "events#register_user", :as => "event_register"

end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :event_users
    has_many :users, :through => :event_users

	attr_accessible :event_name,:header,:sub_header,:banner, :banner600x2000, :bannersquare, :banner1200x2000, :price,:venue,:address,:description,:date,:start_time, :end_time
	attr_accessor :stripe_card_token

	has_attached_file :banner, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	has_attached_file :banner600x2000, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	has_attached_file :bannersquare, :styles => { :medium => "300x300>", :thumb => "100x100>" }
    has_attached_file :banner1200x2000, :styles => { :medium => "300x300>", :thumb => "100x100>" }


	def add_guest(user)
		add_user_with_role(user, :guest)
    end

    def guests
        users_with_roles(:guest)
    end

    def add_guest_to_list(user, opts)
            event_user = GuestList.new
            event_user.event = self
            event_user.user = user
            event_user.send("is_#{role}=", true)
            event_user.save
    end

	private
    def get_event_user_for_user(user)
        event_users.select {|ev| ev.user == user}[0]
    end

    def add_user_with_role(user, role)
    	 event_user = get_event_user_for_user(user)
        if event_user.nil?
            event_user = EventUser.new
            event_user.event = self
            event_user.user = user
        end
        	event_user.send("is_#{role}=", true)
       		event_user.save
    end


    def users_with_role(role)
        event_user.select { |ev| ev.send("is_#{role}?") }
    end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @users = User.all
    @event_users = EventUser.where event_id: params[:id]  
  end

  def checkout
    @event = Event.find(params[:id])
  end

  def register_user
   
    event = Event.find(params[:id])
    if SportsAlliance::StripePaymentCharger.charge(event[:price]*100, :currency => SportsAlliance::PaymentCharger::CURRENCY_USD, :stripe_card_token => params[:checkout][:stripe_card_token], :event => event)
      event.add_guest(current_user)
    end

    redirect_to events_url, status: :see_other
  end


  def invite
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params[:event]
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: { multipart: true } do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :event_name %>
    <%= f.text_field :event_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :header %>
    <%= f.text_field :header, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :sub_header %>
    <%= f.text_field :sub_header, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :banner_450x2000 %>
    <%= f.file_field :banner, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :banner_600x2000 %>
    <%= f.file_field :banner600x2000, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :banner_1200x2000 %>
    <%= f.file_field :banner1200x2000, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :banner_square %>
    <%= f.file_field :bannersquare, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :venue %>
    <%= f.text_field :venue, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :date %>
    <%= f.date_select :date,:start_year => 2013 %>
  </div>
  <div class="form-group">
    <%= f.label :start_time %>
    <%= f.text_field :start_time, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :end_time %>
    <%= f.text_field :end_time, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/events/checkout.html.erb

<div style="background: url(<%= URI.join(request.url, @event.banner1200x2000.url) %>) no-repeat;height:1200px;width:100%;">
	<div style="width:1200px;height:1000px;border:1px solid white;margin:0 auto;">
		<div class="panel panel-default" style="margin:20px 20px 0 125px;width:500px;float:left;">
		  <div class="panel-heading">
		    <h1>Checkout</h1>
		  </div>
		  <div class="panel-body">
			<form accept-charset="UTF-8" action="<%= event_register_url(@event) %>" class="new_checkout" id="new_checkout" method="post">
			<%= token_tag nil -%>
			  <div class="field">
			    <input id="checkout_event_name" name="checkout[event_name]" type="hidden" />
			  </div>
			  <div class="field">
			    <input id="checkout_event_name" name="checkout[event_name]" type="hidden" />
			  </div>
			  <div class="field form-group">
			  	<label for="checkout_email">Email</label><br>
			    <input id="checkout_email" name="checkout[email]" type="text" value="current_user.email" class="form-control" style="width:300px;" />
			  </div>
			  <div class="field form-group">
			    <label for="checkout_first_name">First name</label><br>
			    <input id="checkout_first_name" name="checkout[first_name]" type="text" value="current_user.first_name" class="form-control" style="width:400px;" />
			  </div>
			  <div class="field form-group">
			    <label for="checkout_last_name">Last name</label><br>
			    <input id="checkout_last_name" name="checkout[last_name]" type="text" value="current_user.last_name" class="form-control" style="width:400px;" />
			  </div>

		</div>
		</div>


		<div class="panel panel-default" style="margin:20px 125px 0 20px;width:400px;float:left;">
		  <div class="panel-heading">
		    <h1>Checkout</h1>
		  </div>
		  <div class="panel-body">
			  <div class="field">
			    <input name="checkout[is_admin]" type="hidden" value="0" />
			  </div>
			  <div class="field">
			    <input name="checkout[is_host]" type="hidden" value="0" />
			  </div>
			  <div class="field">
			    <input name="checkout[is_guest]" type="hidden" value="1" />
			  </div>
			  <div class="field">
			    <input id="checkout_stripe_card_token" name="checkout[stripe_card_token]" type="hidden" />
			  </div>
			  <div class="field form-group">
			    <label for="card_number">Credit Card Number</label>
			    <input id="card_number" type="text" class="form-control" style="width:160px;" />
			  </div>
			  <div class="field form-group">
			    <label for="card_code">Security Code on Card (CVV)</label>
			    <input id="card_code" type="text" class="form-control" style="width:70px;" />
			  </div>
			  <div class="field form-group">
			    <label for="card_month">Card Expiration</label>
			    <select id="card_month">
			<option value="1">1 - January</option>
			<option value="2">2 - February</option>
			<option value="3">3 - March</option>
			<option value="4">4 - April</option>
			<option value="5">5 - May</option>
			<option value="6">6 - June</option>
			<option value="7">7 - July</option>
			<option value="8">8 - August</option>
			<option value="9">9 - September</option>
			<option value="10">10 - October</option>
			<option value="11">11 - November</option>
			<option value="12">12 - December</option>
			</select>

			    <select id="card_year">
			<option value="2013">2013</option>
			<option value="2014">2014</option>
			<option value="2015">2015</option>
			<option value="2016">2016</option>
			<option value="2017">2017</option>
			<option value="2018">2018</option>
			<option value="2019">2019</option>
			<option value="2020">2020</option>
			<option value="2021">2021</option>
			<option value="2022">2022</option>
			<option value="2023">2023</option>
			<option value="2024">2024</option>
			<option value="2025">2025</option>
			<option value="2026">2026</option>
			<option value="2027">2027</option>
			<option value="2028">2028</option>
			</select>

			  </div>
			  <div id="stripe_error">
			    <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
			  </div>
			  <div class="actions form-group">
			    <input name="commit" type="submit" value="Register" class="btn btn-primary" />
			  </div>
			</form>
		</div>
		</div>



	</div>
</div>

app/views/events/edit.html.erb
<h1>Editing event</h1>
<div class="container">
	<%= render 'form' %>
</div>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Banner image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.event_name %></td>
        <td><%= image_tag event.banner.url(:medium) %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>
<div class="container">
	<%= render 'form' %>
</div>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div style="background: url(<%= URI.join(request.url, @event.banner600x2000.url) %>) no-repeat;height:600px;width:100%;">
	<div class="container">
		<div class="event-page-header-hold">
			<div class="event-page-header">
				<h1><i><%= @event.header if @event.header %></i></h1>
				<h3><i><%= @event.sub_header if @event.sub_header %></i></h3>
			</div>
			<div class="buy-box">
				<div class="price center">
					<% if user_signed_in? %>
						<%if @event_users.where(:id => current_user.id).blank? %>
							<h3><span class="glyphicon glyphicon-chevron-right"></span> $<%= @event.price if @event.price %> </span></h3><br>
							<p style="font-size:20px;">Current Price</p>
						<% else %>
							<h3><span class="glyphicon glyphicon-chevron-down"></span></span></h3><br>
							<p style="font-size:20px;">You're Going!</p>
						<% end %>
					<% else %>
						<h3><span class="glyphicon glyphicon-chevron-right"></span> $<%= @event.price if @event.price %> </span></h3><br>
						<p style="font-size:20px;">Current Price</p>
					<% end %>

					<% if user_signed_in? %>
						<%if @event_users.where(:id => current_user.id).blank? %>
							<a class="event-login-button center" href="<%= event_checkout_url(@event) %>"><h2>SIGN UP</h2></a>
						<% else %>
							<a class="event-login-button center" href="#"><h2>INVITE FRIENDS</h2></a>
						<% end %>
						<p></p>
						  
					<% else %>

						<a class="event-login-button center" href="/users/auth/facebook"><h2>LOG IN TO BUY</h2></a>
						<p>WE WILL NEVER POST WITHOUT YOUR PERMISSION</p>
	        		<% end %>
				</div>
				<div class="ticketing-close">
					<p>TICKETING WILL CLOSE 3 HOURS BEFORE THE EVENT.  TICKETS CAN BE BOUGHT AT THE DOOR FOR $<%= @event.price if @event.price %> IF AVAILABLE</p>
				</div>
			</div>
		</div>


	</div>
</div>

	<div class="container" style="background: #efefef;margin-top:-140px; margin-bottom:30px;">

			<div style="width:47%;float:left;margin-left:3%;padding-top:15px;padding-right:30px; border-bottom:1px solid black;height:140px;">
				<p><%= @event.description if @event.description %></p>
			</div>
			<div style="width:47%;float:left; margin-right:3%; padding-top:10px; border-bottom:1px solid black;height:140px;">
				<div style="#">
					<div style="width:50%;float:left;border-bottom:1px solid black; border-right:1px solid black;height:50px;">
						<p><span style="padding: 0 10px 20px 0;" class="glyphicon glyphicon-calendar"></span><%= @event.date.strftime("%A, %B #{@event.date.day.ordinalize}") if @event.date %></p>
					</div>
					<div style="width:50%;float:left;border-bottom:1px solid black;border-left:1px solid black;height:50px;">
						<p style="padding: 20px 0 0 10px;"><%= @event.start_time.strftime("%I:%M %P") if @event.start_time %> to <%= @event.end_time.strftime("%I:%M %P") if @event.end_time %></p>
					</div>
				</div>

				<div style="width:100%;height:100%;float:left;" class="center">
					<h2 style="margin-top:12px;font-size:25px;"><%= @event.venue if @event.venue %></h2>
					<p><%= @event.address if @event.address %></p>
				</div>
			</div>

			<div style="float:left;">
				<h2 style="margin:20px 0 0 0;">Committed Fans</h2>
				<% @event_users.each do |eu| %>
					<div class="panel panel-default" style="width:132px; margin:7px;float:left;">
						<img src="<%= @users.find(eu).image %>" alt="<%= @users.find(eu).name %>" width="130" height="130" />
						<div class="panel-body" style="margin:0;padding:0;">
							<p style="padding:3px 0 0 5px;margin:0;"><%= @users.find(eu).first_name.truncate(17) %><br>
								<%= @users.find(eu).last_name.truncate(17) %>
							</p>
						</div>
					</div>
				<% end %>
				
				
			</div>

	</div>










<!--<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>-->