config/routes.rb
Sportsalliance::Application.routes.draw do  resources :events
  resources :charges

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                   controllers: {omniauth_callbacks: "omniauth_callbacks"}

  get "faq" => "pages#faq"
  get "team" => "pages#team"
  get "howitworks" => "pages#how-it-works"
  get "contact" => "pages#contact"
  get "myteams" => "pages#myteams"
  get "myevents" => "pages#myevents"
  root "pages#home"

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  get "/events/:id/checkout" => "events#checkout", :as => "event_checkout"
  get "/events/:id/invite-facebook-friends" => "events#invite", :as => "event_invite"
  post "/events/:id/register" => "events#register_user", :as => "event_register"

end

app/views/layouts/_footer.html.erb
<div class="navbar">
	<section class="bottom-links">
		<div class="container">
			<div class="bottom-links-holder">
				<%= link_to "How it Works", howitworks_path, :class=>"bottom-nav-links" %>
				<%= link_to "FAQ", faq_path, :class=>"bottom-nav-links" %>
				<%= link_to "Contact", contact_path, :class=>"bottom-nav-links" %>
				<%= link_to "Team", team_path, :class=>"bottom-nav-links" %>
			</div>
		</div>
	</section>
	<section class="copyright-section">
		<div class="container">
			<div style="margin-top:10px"
				<p>© 2013 Sports Alliance</p>
			</div>
		</div>
	</section>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default .navbar-fixed-top nav-shadow" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header navbar-header-logo">
    <%= link_to image_tag("fannetic-logo.png"), root_path, :class=>"navbar-logo" %>
  </div>
  <% if user_signed_in? %>
    <div class="navbar-header">
      <%= link_to "My Events", myevents_path, :class=>"nav-links" %>
    </div>
    <div class="navbar-header">
      <%= link_to "My Teams", myteams_path, :class=>"nav-links" %>
    </div>
  <% end %>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <%= current_user.first_name.upcase %>  <span class="glyphicon glyphicon-chevron-down"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'SETTINGS', edit_user_registration_path %></li>
            <li><%= link_to "SIGN OUT", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "", user_omniauth_authorize_path(:facebook), :class=>"facebook-login" %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fannetic</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/", "application", "data-turbolinks-track" => true %>
  <script type='text/javascript'>
    $(document).ready(
      function() {
         $('.carousel').carousel({
             interval: 5000
         })
    });


</script>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
</head>
<body>
	<%= render 'layouts/header' %>

	<!--<% flash.each do |name, msg| %>
    	<%= content_tag(:div, msg, class: "alert alert-info") %>
	<% end %>-->
	<%= yield %>

  <%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>